# Generated by Django 3.0.6 on 2020-05-21 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('bancada', models.CharField(max_length=100)),
                ('periodo', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoyo', models.IntegerField()),
                ('telefonia', models.IntegerField()),
                ('traslacion', models.IntegerField()),
                ('difusion', models.IntegerField()),
                ('interaccion', models.IntegerField()),
                ('arriendo', models.IntegerField()),
                ('consumos_basicos', models.IntegerField()),
                ('equipamiento', models.IntegerField()),
                ('art_oficina', models.IntegerField()),
                ('correspondencia', models.IntegerField()),
                ('mant_oficina', models.IntegerField()),
                ('repar_inmueble', models.IntegerField()),
                ('habil_sede', models.IntegerField()),
                ('seguro', models.IntegerField()),
                ('arriendo_ov', models.IntegerField()),
                ('web', models.IntegerField()),
                ('almacenamiento', models.IntegerField()),
                ('arriendo_om', models.IntegerField()),
                ('mant_om', models.IntegerField()),
                ('menores', models.IntegerField()),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Deputy')),
            ],
        ),
    ]
